#!/bin/bash

# SPDX-FileCopyrightText: 2020 jecoz
#
# SPDX-License-Identifier: MIT

# di-cache is an helper script for running a redis-server instance.

source dirc

main() {
	if [ ! -x $redis ]; then
		error "missing required executable: $redis"
		info "you can install it with homebrew (https://brew.sh) running:"
		info "% brew install redis"
		exit 1
	fi

	info "cache server address: localhost:${cache_port}"
	$redis -p ${cache_port}
}

main
