#!/bin/bash

# SPDX-FileCopyrightText: 2020 jecoz
#
# SPDX-License-Identifier: MIT

# di-cache is an helper script for running a redis-server instance.

cd `dirname "${BASH_SOURCE[0]}"`
source dirc

main() {
	if [ ! -x $redis ]; then
		error "missing required executable: $redis"
		info "you can install it with homebrew (https://brew.sh) running:"
		info "% brew install redis"
		exit 1
	fi

	$redis --port ${cache_port}
}

main
