#!/bin/bash

# SPDX-FileCopyrightText: 2020 jecoz
#
# SPDX-License-Identifier: MIT

main() {
	cd `dirname "${BASH_SOURCE[0]}"`
	source dirc

	if [ ! -x $dic ]; then
		error "missing required executable: $dic"
		info "you can compile the executable with:"
		info "% make"
		exit 1
	fi
	if [ ! -x $dis ]; then
		error "missing required executable: $dis"
		info "you can compile the executable with:"
		info "% make"
		exit 1
	fi

	mkdir -p ${wd}
	touch ${trfile}
	touch ${dicout}
	echo "--- reading transcript from ${trfile}"
	tail -f ${trfile} | $dic | tee ${dicout} | $dis -p ${server_port} --sd "${wd}/images"
}

main $@
