#!/bin/bash

# SPDX-FileCopyrightText: 2020 jecoz
#
# SPDX-License-Identifier: MIT

cd `dirname "${BASH_SOURCE[0]}"`
source dirc

main() {
	if [ ! -x $dic ]; then
		error "missing required executable: $dic"
		info "you can compile the executable with:"
		info "% make"
		exit 1
	fi
	if [ ! -x $dis ]; then
		error "missing required executable: $dis"
		info "you can compile the executable with:"
		info "% make"
		exit 1
	fi

	for arg in "$@"
	do
		case $arg in
			-c|--cache)
			cache_flag="-ra localhost:${cache_port}"
			shift
			;;
		esac
	done

	mkdir -p ${wd}
	touch ${trfile}
	tail -f ${trfile} | $dic $cache_flag | $dis -p ${server_port}
}

main $@
