#!/bin/bash

# SPDX-FileCopyrightText: 2020 jecoz
#
# SPDX-License-Identifier: MIT

error() {
	echo >&2 "`basename $0` * error: $1"
}

info() {
	echo >&2 "`basename $0` * $1"
}

ffmpeg=`command -v ffmpeg`
rtmpsrv=bin/listenrtmp
trnscr=bin/trnscr
dic=bin/dic
dis=bin/dis

wd="workdir"
logfile="${wd}/sgtr.log"
trfile="${wd}/transcript.strr"
dicout="${wd}/transcript+images.csv"

lang="de-DE"
cache_port=7746
server_port=7745
rtmp_port=3500
